project:
  type: website

format:
  html:
    theme: default
    css: gatech-theme.css
    number-sections: true
    html-math-method: mathml
    toc: false
    embed-resources: false

execute:
  freeze: auto
