project:
  type: website

website:
  title: "PHYS 4604"
  navbar:
    background: "#003057"
    foreground: "#EAAA00"
    pinned: true
    search: true
    left:
      - text: "Course Files"
        menu:
          - course-files\syllabus.qmd
          - course-files\ai-usage-statement.qmd
      - text: "Assignments"
        menu:
          - assignments/resume.qmd
          - assignments/online-profile.qmd
          - assignments/research-proposal.qmd
          - assignments/personal-statement.qmd
          - assignments/external-participation.qmd
      - text: "Supplemental"
        menu:
          - supplemental/resume-cv.qmd
          - supplemental/technical-writing.qmd
          - supplemental/peer-feedback.qmd
      - text: "Lectures"
        href: lectures/index.qmd

format:
  html:
    theme: default
    css: gatech-theme.css
    number-sections: true
    html-math-method: mathml
    toc: false
    embed-resources: false

bibliography: references.bib

execute:
  freeze: auto
