project:
  type: website

website:
  title: "PHYS 4604"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Syllabus"
        href: course-files/syllabus.qmd
      - text: "Assignments"
        menu:
          - assignments/resume.qmd
          - assignments/online-profile.qmd
          - assignments/research-proposal.qmd
          - assignments/personal-statement.qmd
          - assignments/external-participation.qmd
      - text: "Supplemental"
        menu:
          - supplemental/resume-cv.qmd
          - supplemental/technical-writing.qmd
      - text: "Lectures"
        menu:
          - lectures/lecture-01.qmd

format:
  html:
    theme: default
    css: gatech-theme.css
    number-sections: true
    html-math-method: mathml
    toc: false
    embed-resources: false

execute:
  freeze: auto
